services:
  tana-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:80"

  tana-web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5174:80"
    depends_on:
      - tana-api
